openapi: 3.0.1
info:
  title: My First Service
  x-cortex-tag: my-first-service
  x-cortex-owners:
    - type: email
      email: taylor.schmidt@cortex.io
  x-cortex-dashboards:
    embeds:
      - type: datadog
        url: https://app.datadoghq.com/graph/embed?token=102fe9af16ff921a5af504c65edc71ea5211713fded23b5c98835ed51a8769ff&height=300&width=600&legend=true
  x-cortex-git:
    github:
      repository: THS-Org/cortex-support
  x-cortex-dependency:
    - tag: testtest
    
